### ISSUE TITLE
CementController

### ISSUE THREAD

**Issue by psychomad** [abhi-r3v0/Adhrit#31]
Installing Adhrit on Kali 2019.4 with all dependencies i have this error:

Traceback (most recent call last):
  File "adhrit.py", line 17, in <module>
    from recons.smarser.parser import parser
  File "/media/root/Mandalorian/codeX/Adhrit/recons/smarser/parser.py", line 4, in <module>
    from smalisca.core.smalisca_main import SmaliscaApp
  File "/usr/local/lib/python3.7/dist-packages/smalisca/core/smalisca_main.py", line 39, in <module>
    from smalisca.controller.controller_base import BaseController
  File "/usr/local/lib/python3.7/dist-packages/smalisca/controller/controller_base.py", line 40, in <module>
    class BaseController(controller.CementBaseController):
AttributeError: module 'cement.core.controller' has no attribute 'CementBaseController'

I was wondering the cement version was too new so i downgrade cement version from 3 to 2 and everything work.
I just wanted to share this with everyone that will install adhrit on new kali versioni (2019.4)
Regards!

**Comment by abhi-r3v0** [comment]
Hi @psychomad 

Thanks for reporting!
I guess cement versions are too unstable. A possible workaround I can see is a docker image, which I'm building right now. Will soon push it!

Regards!
