### ISSUE TITLE
No module named 'smalisca' error in parser.py

### ISSUE THREAD

**Issue by bk-rao** [abhi-r3v0/Adhrit#32]
I am not able to run the main project and I am getting an error in parser.py that a module is not present and all dependencies mentioned in installer.py are installed on my OS. I think these folders are missing.

Error:
Traceback (most recent call last):
  File "adhrit.py", line 17, in <module>
    from recons.smarser.parser import parser
  File "/root/Downloads/Android Pentest Setup/Main Tools/Adhrit/recons/smarser/parser.py", line 4, in <module>
    from smalisca.core.smalisca_main import SmaliscaApp
ModuleNotFoundError: No module named 'smalisca'

**To Reproduce**
'python3 adhrit.py -help' or 'python3 adhrit.py' both times I am getting error

OS: Kali Linux 2019.4
Kali Linux is installed in vmware.

![Uploading adhrit_error.PNG…]()

**Comment by abhi-r3v0** [comment]
Hi @bk-rao,

Thanks for reporting! I initially thought the smalisca installation errors were specific to my machine. I think dockerizing might help. Will push an update soon.

Regards

**Comment by bk-rao** [comment]
I was able to solve it in my machine. Problem lies in latest versions of python and it modules. Reducing them works similar to the previous cement controller issue. I think docker is the best thing to go forward. Thank You

**Comment by adityhere** [comment]
> I was able to solve it in my machine. Problem lies in latest versions of python and it modules. Reducing them works similar to the previous cement controller issue. I think docker is the best thing to go forward. Thank You

can you please checkout my implemantation of docker for Adhrit https://github.com/adityhere/Adhrit/tree/docker/docker
