### ISSUE TITLE
Mac OS error

### ISSUE THREAD

**Issue by Teicu** [abhi-r3v0/Adhrit#34]
Hi all 

any help to solve this issue please?  

Thank you

> Traceback (most recent call last):
>   File "adhrit.py", line 17, in <module>
>     from recons.smarser.parser import parser
>   File "/Users/x/Adhrit/recons/smarser/parser.py", line 4, in <module>
>     from smalisca.core.smalisca_main import SmaliscaApp
>   File "/usr/local/lib/python3.7/site-packages/smalisca/core/smalisca_main.py", line 39, in <module>
>     from smalisca.controller.controller_base import BaseController
>   File "/usr/local/lib/python3.7/site-packages/smalisca/controller/controller_base.py", line 40, in <module>
>     class BaseController(controller.CementBaseController):
> AttributeError: module 'cement.core.controller' has no attribute 'CementBaseController'

**Comment by abhi-r3v0** [comment]
Hi @Teicu 

Thanks for reporting the issue. This is an error with the Cement library which has been giving everyone a hard time. We're trying to find a permanent solution for this. But meanwhile, you can downgrade the Cement version and try (this has helped previously). For help, refer to the `installer.py` file and the previously reported issues. 

Regards

**Comment by Teicu** [comment]
Hi mate 

thank you for your answer.  

I have already installed cement 2.10.12 and deleted all others version, but seems useless. I get the same error :(

[+]  Installation of Android tools complete
	[+] Installed PrettyTable
	[+] Installed requests
	[+] Installed progressbar2
	[+] Installed colorama
	[+] Installed urllib3
	[+] Installed Jinja2
	[+] Installed r2pipe
	[+] Installed smalisca
	[+] Installed cement==2.10.12

**Comment by Teicu** [comment]
> [+]  Installation of Android tools complete
> 	[+] Installed PrettyTable
> 	[+] Installed requests
> 	[+] Installed progressbar2
> 	[+] Installed colorama
> 	[+] Installed urllib3
> 	[+] Installed Jinja2
> 	[+] Installed r2pipe
> 	[+] Installed smalisca
> 	[+] Installed cement==2.10.12
> 
> [+] Installation of MacOS dependencies complete. Check with 'python3 adhrit.py -h'
> Pentest@x Adhrit % python3 adhrit.py -h
> Traceback (most recent call last):
>   File "adhrit.py", line 17, in <module>
>     from recons.smarser.parser import parser
>   File "/Users/x/Adhrit/recons/smarser/parser.py", line 4, in <module>
>     from smalisca.core.smalisca_main import SmaliscaApp
>   File "/usr/local/lib/python3.7/site-packages/smalisca/core/smalisca_main.py", line 38, in <module>
>     from smalisca.core.smalisca_logging import log
>   File "/usr/local/lib/python3.7/site-packages/smalisca/core/smalisca_logging.py", line 36, in <module>
>     from cement.ext.ext_logging import LoggingLogHandler
> ModuleNotFoundError: No module named 'cement'

**Comment by Teicu** [comment]
> Pentest@x Adhrit % sudo pip install cement==2.10.12
> 
> Requirement already satisfied: cement==2.10.12 in /Library/Python/3.7/site-packages (2.10.12) 

so wtf

**Comment by PSNAppz** [comment]
Try this manually

`pip install cement==2.10.2`
