### ISSUE TITLE
 FileNotFoundError: [Errno 2] No such file or directory: '/app/radare2/sys' while installing using docker

### ISSUE THREAD

**Issue by harishsg99** [abhi-r3v0/Adhrit#52]
**Describe the bug**

**To Reproduce**
1. Install this using docker

**Error**

Traceback (most recent call last):
#9 524.0   File "/app/adhrit/installer.py", line 163, in <module>
#9 524.0     main()
#9 524.0   File "/app/adhrit/installer.py", line 160, in main
#9 524.0     dep.ins()
#9 524.0   File "/app/adhrit/installer.py", line 49, in ins
#9 524.0     os.chdir(working_dir + '/radare2/sys')
#9 524.0 FileNotFoundError: [Errno 2] No such file or directory: '/app/radare2/sys'

**Desktop (please complete the following information):**
 - OS: Docker

**Smartphone (please complete the following information):**

**Additional context**

**Comment by abhi-r3v0** [comment]
@rahul-sani maybe we should add a check to verify successful download of radare2

**Comment by harishsg99** [comment]
Well, I will try to contribute code to check for successful download of radare2
