### ISSUE TITLE
pyfiglet.FontNotFound: larry3d 

### ISSUE THREAD

**Issue by mithunshaji** [abhi-r3v0/Adhrit#54]
I have tried to install different pyfiglet package still the issue is not solved

Traceback (most recent call last):
  File "/home/psyhax/Adhrit/app.py", line 12, in <module>
    from adhrit.recons.smarser.parser import parser
  File "/home/psyhax/Adhrit/adhrit/recons/smarser/parser.py", line 4, in <module>
    from smalisca.core.smalisca_main import SmaliscaApp
  File "/usr/local/lib/python3.9/dist-packages/smalisca/core/smalisca_main.py", line 37, in <module>
    import smalisca.core.smalisca_config as config
  File "/usr/local/lib/python3.9/dist-packages/smalisca/core/smalisca_config.py", line 73, in <module>
    class HelpMessage:
  File "/usr/local/lib/python3.9/dist-packages/smalisca/core/smalisca_config.py", line 77, in HelpMessage
    f = Figlet(font='larry3d')
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 794, in __init__
    self.setFont()
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 801, in setFont
    self.Font = FigletFont(font=self.font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 126, in __init__
    self.data = self.preloadFont(font)
  File "/usr/lib/python3/dist-packages/pyfiglet/__init__.py", line 147, in preloadFont
    raise FontNotFound(font)
pyfiglet.FontNotFound: larry3d

**Comment by rahul-sani** [comment]
@mithunshaji Reinstalling pyfiglet should be solving this issue. Try reinstalling once using the command below.

`python3 -m pip install pyfiglet`
